### ISSUE TITLE
Unique "key" prop warning in v7.2.3

### ISSUE THREAD

**Issue by rkallan** [storybookjs/addon-jsx#105]
React v16.13.1
Storybook v5.3
storybook-addon-jsx v7.2.3

After clicking on the jsx tab i get this warning

> Warning: Each child in a list should have a unique "key" prop.

![image](https://user-images.githubusercontent.com/8122055/79490040-8b232f80-801c-11ea-8cf2-8e5135fdffcf.png)

In file: src/register.tsx on line 30 

`render: ({ active }) => <JSX key="addon-jsx" active={active} ob={ob} />`

changing to

render: ({ active }) => <JSX key={\`addon-jsx-\`${+ active}} active={active} ob={ob} />

Solved the waring message. But when changing story when jsx tab is active the warning is showing again.

FYI: i have tested this changing the file in my node_module folder

**Comment by lisamartin00** [comment]
I also get this if I try to remove functions from showing up as js via this approach:
https://github.com/storybookjs/addon-jsx/issues/114#issuecomment-656753751

or any kind of approach like this that pass in options to `react-element-to-jsx-string`:
https://github.com/storybookjs/addon-jsx/issues/30#issuecomment-517548309

removing these approaches solves the warning message as well, but isn't an ideal long-term solution

**Comment by hipstersmoothie** [comment]
Anyone want to make a PR for this?

**Comment by lisamartin00** [comment]
Happy to give it a stab later tonight unless someone else beats me to it
