### ISSUE TITLE
Feature: HTML Syntax Highlighting

### ISSUE THREAD

**Issue by petermikitsh** [storybookjs/addon-jsx#106]
I have been overloading the JSX tab to display not only React, but Angular and HTML. React and Angular render great! HTML does pretty well too, minus `<script>` tags:

<img width="1050" alt="Screen Shot 2020-04-23 at 9 39 05 PM" src="https://user-images.githubusercontent.com/1571918/80175708-37c85880-85ab-11ea-8918-8613c9f89f65.png">

Thoughts on supporting plain HTML? I will defer to maintainers. Thanks!

Reference images:

| Angular | React |
|-------|---------|
|  <img width="1055" alt="Screen Shot 2020-04-23 at 9 43 15 PM" src="https://user-images.githubusercontent.com/1571918/80175783-7d852100-85ab-11ea-8c93-e90d7403db47.png">     |     <img width="1053" alt="Screen Shot 2020-04-23 at 9 44 03 PM" src="https://user-images.githubusercontent.com/1571918/80175827-9b528600-85ab-11ea-95b5-2a5e0f784db7.png">    |

**Comment by hipstersmoothie** [comment]
Yeah I'm down. The name of this plugin (and the panel title) might be a little misleading though.

Are you using something other than https://github.com/storybookjs/addon-jsx#not-jsx?

**Comment by petermikitsh** [comment]
I've found I can get this feature for free with https://www.npmjs.com/package/@storybook/addon-storysource. That'll work in this use case!
