### ISSUE TITLE
Does this work with Component Story Format (CSF)?

### ISSUE THREAD

**Issue by BrendanBerkley** [storybookjs/addon-jsx#107]
Sorry if this has been asked before. I'm upgrading and trying to migrate to CSF, and I've been having problems using this addon in the new environment.

The docs seem to use storiesOf exclusively.

In my main.js, I added `addons: [ [...], 'storybook-addon-jsx']`, and in my stories.tsx file I added `decorators: [jsxDecorator]` to the metadata. This gets the JSX tab to show, but it triggers some kind of recursion in the browser, because I have to kill the tab. The warning I get when I do so says `Script terminated by timeout at: createElementWithValidation`.

**Comment by hipstersmoothie** [comment]
It should work.

Have you tried adding it as a global decorator?

**Comment by BrendanBerkley** [comment]
If I'm reading the docs right, config.js is no longer a thing, it's preview.js now?

My preview.js looks like this

```
import { configure, addDecorator } from '@storybook/react';
import { jsxDecorator } from 'storybook-addon-jsx';

addDecorator(jsxDecorator);

configure(require.context('../src', true, /\.stories\.tsx$/), module);
```

But while your example shows `storiesOf('Vue', module)` as a way to use `module`, I don't see an equivalent in the CSF docs.

Anyways, I got the same result.

If you're confident it works, then you don't need to help me debug. Knowing it's my problem is helpful information. Thanks for getting back to me!

**Comment by hipstersmoothie** [comment]
this might be an issue with the new 6.0 config style. I am unfamiliar with it at this point and haven't. tried it myself. I don't *think* it should require any changes to this plugin, but not entirely sure.

If you find out what works for 6.0 please contribute to the docs! I don't have the time right now to look deeper right now.

@ndelangen @shilman Is @BrendanBerkley doing the right configuration for the new configuration style?

**Comment by bohdanbirdie** [comment]
Also looking into support for this
Haven't got it running so far

**Comment by ulysset** [comment]
Hi,
I managed to make the global configuration work in 6.0
First in `.storybook/main.js` you need to have the `storybook-addon-jsx` addon like so :
```javascript
// .storybook/main.js
module.exports = {
  addons: ['storybook-addon-jsx'],
};
```
Finally add the `jsxDecorator` to `.storybook/preview` :
```javascript
// .storybook/preview.js
import { addDecorator } from '@storybook/react';
import { jsxDecorator } from 'storybook-addon-jsx';

addDecorator(jsxDecorator);
```
Id didn't need the `configure` from `@storybook/react`

**Comment by aliahsan07** [comment]
Has anyone found a solution to this issue?

**Comment by hipstersmoothie** [comment]
If someone could make a minimal reproduction repo that would be awesome. In my project it works fine. Here is what I have configured:

**`.storybook/main.js`**

```js
module.exports = {
  addons: [
    'storybook-addon-jsx'
  ]
};
```

**`.storybook/preview.js`**

```js
const { addDecorator } = require('@storybook/react');
const { jsxDecorator } = require('storybook-addon-jsx');

addDecorator(jsxDecorator);
```

So exactly the same as @ulysset

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in [`v7.3.1`](https://github.com/storybookjs/addon-jsx/releases/tag/v7.3.1) :rocket:

**Comment by aliahsan07** [comment]
If this works, it might be worth adding to the readme.

**Comment by hipstersmoothie** [comment]
Check the readme. Already did it 🚀
