### ISSUE TITLE
How to disable this addon for a single story?

### ISSUE THREAD

**Issue by petermikitsh** [storybookjs/addon-jsx#109]
For other stories, to disable a plugin (in the example, named `centered`), I do the following:

```tsx
export const Simple = () => {
  return <div>Hello World</div>;
};

Simple.story = {
  parameters: {
    centered: {
      disable: true,
    },
  },
};
```

To my understanding, I am using component story format (CSF): https://storybook.js.org/docs/formats/component-story-format/

I have the JSX addon enabled globally, for all stories. Is it possible to disable the addon for a single story in CSF mode?

Context: I am rendering a table component, and the story is serving as a performance test with 1 million table rows. Creating the JSX for this story is expensive (which is totally reasonable) and the browser slows down. Since the story is only for performance, I don't need the JSX addon tab.

**Comment by hipstersmoothie** [comment]
I def feel like you should be able to. But If it doesn't I'll happily merge a PR!
