### ISSUE TITLE
Docs are unclear

### ISSUE THREAD

**Issue by ismay** [storybookjs/addon-jsx#112]
The docs for this plugin are quite unclear for a newcomer to this plugin:

* Seems to mix examples for vue and react without clearly indicating which is which
* Code examples without clear indication what we're looking at, is it a configuration file, a story?

Especially enabling this plugin globally could use a lot more clear instructions, but in general it just seems like they could use a bit of care and attention. Meant as constructive criticism, thanks for the plugin!

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in [`v7.3.1`](https://github.com/storybookjs/addon-jsx/releases/tag/v7.3.1) :rocket:
