### ISSUE TITLE
Allow JSX customization (boolean props, etc)

### ISSUE THREAD

**Issue by aleph-naught2tog** [storybookjs/addon-jsx#124]
It'd be cool if this let you set some basic configuration options on styling. For example, in our project we require boolean props to have a value, so `disabled` isn't sufficient, rather we prefer `disabled={true}`. This addon, however, transforms it to `disabled` in the actual JSX displayed, which means someone copying and pasting examples would have to fix it themselves. Similarly with `<React.Fragment>` being transformed to `<>`, etc. (Or if there is a way to do this, please let me know!)

This is a great addon, and I really appreciate how well it works right out the gate and all the little features like showing the type definition when hovering over a prop, etc. 😄

**Comment by hipstersmoothie** [comment]
This plugin support all options that [react-element-to-jsx-string](https://github.com/algolia/react-element-to-jsx-string#api) does. So I think you want to set `useBooleanShorthandSyntax` and `useFragmentShortSyntax to `false`.

Do those meet your needs?

**Comment by aleph-naught2tog** [comment]
@hipstersmoothie Oh, that's perfect, thank you!
