### ISSUE TITLE
[Bug] Copy Button Moves on Scroll

### ISSUE THREAD

**Issue by mosherc** [storybookjs/addon-jsx#134]
### Describe the bug

When the content of the JSX preview is tall enough to be scrollable, when you scroll down, the "Copy" button will scroll with the content. I would expect the copy button to stay fixed at the top or bottom.

### Steps to reproduce the behavior

1. Create a story with a large amount of JSX
2. Open the JSX panel
3. Scroll down
4. See "Copy" button move up as you scroll down

### Expected behavior

I would expect the Copy button to stay fixed at the bottom as I scroll.

### Screenshots and/or logs

![image](https://user-images.githubusercontent.com/7862535/107239555-f8161480-69f6-11eb-8958-eaab2b65d3bb.png)

### Environment

 - OS: macOS 11 Big Sur
 - Node.js version: 10.16.3
 - NPM version: 6.9.0
 - Browser (if applicable): Chrome 88
 - Browser version (if applicable): 88
 - Device (if applicable): M1 MacBook Pro 2020

### Additional context

I believe there are a couple ways to fix this. This button is positioned absolute in an absolute positioned parent (the JSX content preview), which I believe is the issue. This could be fixed by making it position fixed and adding some pixels to the position, or if possible, move it a little further up the DOM tree such as into `#panel-tab-content`.

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in [`v7.3.6`](https://github.com/storybookjs/addon-jsx/releases/tag/v7.3.6) :rocket:

**Comment by mosherc** [comment]
Fixed, thanks!
