### ISSUE TITLE
[Bug] React 17 peer dependency

### ISSUE THREAD

**Issue by Wunsz** [storybookjs/addon-jsx#140]
### Describe the bug

Cannot install `storybook/addon-jsx` in project using React 17.

### Steps to reproduce the behavior

1. Create a project with `"react": "^17.0.1"` and the newest Storybook
2. Issue command:
```
npm i --save-dev storybook-addon-jsx
```

### Expected behavior
JSX addon is installed correctly.

### Screenshots

![image](https://user-images.githubusercontent.com/11278533/111153828-b72f9380-8592-11eb-854d-6d86ec6f0895.png)

### Environment

 - OS: Ubuntu 20.10
 - Node.js version: v15.6.0
 - NPM version: 7.4.0
 - Browser (if applicable): N/A
 - Browser version (if applicable): N/A
 - Device (if applicable): N/A

### Additional context
N/A

**Comment by leepowelldev** [comment]
Are there any plans to fix this? This repo seems fairly inactive. Happy to create a PR if that will get this through sooner as it's a blocker for us right now.

**Comment by hipstersmoothie** [comment]
Make a PR and I'll merge it :D

**Comment by leepowelldev** [comment]
https://github.com/storybookjs/addon-jsx/pull/142

**Comment by leepowelldev** [comment]
Can't tell what the PR is failing on as it's running in Circle. Seems like all PR's are having the issue though.
