### ISSUE TITLE
Export + Export Default + React Hooks

### ISSUE THREAD

**Issue by hipstersmoothie** [storybookjs/addon-jsx#46]
Hi, Thanks for the awesome plugin. 

Currently I am using typescript + docgen to get a prop table for my components. To do this I have to export my component as default export + non default:

```js
export function Component() {}
export default Component;
```

when I add `export function Component() {}` i get the following error from react 16.7.0-alpha

<img width="1427" alt="screen shot 2018-10-31 at 11 20 29 am" src="https://user-images.githubusercontent.com/1192452/47809808-0268e480-dcff-11e8-80a7-fa62ba780120.png">

**Comment by hipstersmoothie** [comment]
I somehow got past that. but now i'm encountering a bug where. the above config. makes the jsx rendering wrong sometimes.

<img width="182" alt="screen shot 2018-10-31 at 11 35 33 pm" src="https://user-images.githubusercontent.com/1192452/47836489-b735ec80-dd65-11e8-8794-c58d7e84ee0b.png">
<img width="282" alt="screen shot 2018-10-31 at 11 35 43 pm" src="https://user-images.githubusercontent.com/1192452/47836490-b8ffb000-dd65-11e8-8540-e75ccdc36c97.png">

**Comment by hipstersmoothie** [comment]
More on Hooks: I had a wrapper component in a decorator which i moved to the addWithJSX fn and the error doesnt throw now. Problem is i cant get the wrapper to not render

**Comment by vipcxj** [comment]
Why closed it? I met the same issure, too.

**Comment by hipstersmoothie** [comment]
hooks issue tracking in #84
