### ISSUE TITLE
 Cannot read property 'register' of undefined

### ISSUE THREAD

**Issue by feonit** [storybookjs/addon-jsx#58]
Deps:  
  "@storybook/addon-actions": "^4.1.11",
    "@storybook/addon-info": "4.1.11",
    "@storybook/addon-knobs": "4.1.11",
    "@storybook/addon-options": "4.1.11",
    "@storybook/cli": "4.1.11",
    "@storybook/react": "4.1.11",

    "storybook-addon-jsx": "^7.0.1" 

Upped from 6 version to 7 and catch error.

**Comment by hipstersmoothie** [comment]
v7 broke because it switches support to v5 of storybook. I can try to get v4 working again or make a PR 

https://github.com/storybooks/addon-jsx/releases/tag/v7.0.0
