### ISSUE TITLE
Not reading configuration

### ISSUE THREAD

**Issue by kevinwolfdev** [storybookjs/addon-jsx#72]
The third argument for `addWithJSX` is not working, even on the online storybook: https://storybooks-addon-jsx.netlify.com/?path=/story/simple-test--no-children-no-options

**Comment by plysik** [comment]
Is someone going to fix this?

**Comment by third** [comment]
I encountered the same issue. It seems that the global options are still respected but not options specific to a story added with addWithJSX.

I created this PR #95

**Comment by plysik** [comment]
How do you use global settings?

**Comment by third** [comment]
On the README, it says

## Global Options

To configure global options for this plugin, add the following to your `config.js`.

```js
import { addParameters } from '@storybook/react';

addParameters({
  jsx: {
    // your options
  }
});
```
