### ISSUE TITLE
Boolean prop not displaying

### ISSUE THREAD

**Issue by dennisc9** [storybookjs/addon-jsx#85]
When adding a prop as boolean false it does not show in the pane.

`<Component propName={false} />`

In output you will just see `<Component />`

**Comment by michaelthorne** [comment]
Just ran into the same issue. Bit of a dealbreaker.

Unfortunate, as this is an otherwise useful addon.

**Comment by hipstersmoothie** [comment]
For this you just have to configure [the library this addon is built on](https://github.com/algolia/react-element-to-jsx-string) specifically:

![Screen Shot 2020-03-19 at 8 48 59 AM](https://user-images.githubusercontent.com/1192452/77086097-82f4b780-69be-11ea-916d-b2696d1e6994.png)
