### ISSUE TITLE
addWithJSX syntax not working with Typescript

### ISSUE THREAD

**Issue by FancyVase** [storybookjs/addon-jsx#94]
I was able to get `typescript-addon-jsx` working with `.addDecorator(jsxDecorator)`, but I'm having some trouble using the `.addWithJSX` syntax. I'm getting the following TS error:
```sh
ERROR in [at-loader] ./src/Button/Button.story.tsx:18:9
    TS2349: This expression is not callable.
  Not all constituents of type 'string | ClientApiReturnFn<ReactElement<unknown, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)>>' are callable.
    Type 'string' has no call signatures.
```

I'm using `storybook-addon-jsx@7.1.13` and tried installing both `@types/storybook-addon-jsx` as well as `@types/storybook__react`, but I get the same TS error.

--------

If I navigate to the types declaration of `.addWithJSX()` that takes me to `node_modules/.../@storybook/addons/dist/types.d.ts`, which shows:
```tsx
export interface StoryApi<StoryFnReturnType = unknown> {
    kind: string;
    add: (storyName: string, storyFn: StoryFn<StoryFnReturnType>, parameters?: Parameters) => StoryApi<StoryFnReturnType>;
    addDecorator: (decorator: DecoratorFunction<StoryFnReturnType>) => StoryApi<StoryFnReturnType>;
    addParameters: (parameters: Parameters) => StoryApi<StoryFnReturnType>;
    [k: string]: string | ClientApiReturnFn<StoryFnReturnType>;
}
```

Seems like the line `[k: string]: string...` is catching the `.addWithJSX` call, so I'm not sure the declaration merge (which I assume is what `@types/storybook-addon-tsx` is doing) worked as intended, but does anyone know if it's possible to use `.addWithJSX()` with Typescript? If not, is there a way to pass in options to the addon when using the decorator syntax?

Thanks!

**Comment by FancyVase** [comment]
As a workaround I can cast my story to `any`, but I don't think this approach is ideal:
```tsx
const stories = storiesOf('Button', module) as any;
```

**Comment by FancyVase** [comment]
As another workaround I was able to do
```tsx
import JSXAddon from 'storybook-addon-jsx'

const stories = storiesOf('Button', module);
stories.addWithJSX = JSXAddon.addWithJSX;
```

Not great, but it got the job done. 

I ended up switching to the decorator syntax though and it's working now (initially I wasn't able to set `jsx` options for some reason) so I'll go with that approach and close this issue.

**Comment by doublejosh** [comment]
This second approach doesn't seem to work for me...

```
Type '(this: StoryApi<unknown>, kind: string, storyFn: StoryFn<any>) => StoryApi<unknown>' is not assignable to type 'string | ClientApiReturnFn<StoryFnReactReturnType>'.
  Type '(this: StoryApi<unknown>, kind: string, storyFn: StoryFn<any>) => StoryApi<unknown>' is not assignable to type 'ClientApiReturnFn<StoryFnReactReturnType>'.
    Call signature return types 'StoryApi<unknown>' and 'StoryApi<StoryFnReactReturnType>' are incompatible.
      The types of 'addDecorator' are incompatible between these types.
        Type '(decorator: DecoratorFunction<unknown>) => StoryApi<unknown>' is not assignable to type '(decorator: DecoratorFunction<StoryFnReactReturnType>) => StoryApi<StoryFnReactReturnType>'.
          Types of parameters 'decorator' and 'decorator' are incompatible.
            Types of parameters 'fn' and 'fn' are incompatible.
              Type 'StoryFn<unknown>' is not assignable to type 'StoryFn<StoryFnReactReturnType>'.
                Type 'unknown' is not assignable to type 'StoryFnReactReturnType'.ts(2322)
```
