### ISSUE TITLE
Props with defaultProps of `undefined` show up.

### ISSUE THREAD

**Issue by leonelgalan** [storybookjs/addon-jsx#96]
Story definition:

```jsx
<Checkbox
  onChange={onChange}
  value="yes"
  label="Check the Box"
/>
```

Storybook's JSX:

```jsx
<Checkbox
  checked={false}
  color={undefined}
  id={undefined}
  label="Check the Box"
  name={undefined}
  onChange={action('onChange')}
  value="yes"
/>
```

Looking for a solution I noticed a [PR](https://github.com/algolia/react-element-to-jsx-string/pull/417) that just got merged in _react-element-to-jsx-string_, but _react-element-to-jsx-string_ is locked to ^14.0.3.

It allows for `filterProps` to be a function, so one could exclude props where the value is `undefined`.

**14.3.0** was just released. There are [no breaking changes since 14.0.3](https://github.com/algolia/react-element-to-jsx-string/blob/v14.3.0/CHANGELOG.md), but features that might benefit the community.

**Comment by leonelgalan** [comment]
While preparing the PR (#97) I noticed _14.3.0_ wouldn't work. Since _14.3.1_ was released and it includes the fixes needed (https://github.com/algolia/react-element-to-jsx-string/pull/516)

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in v7.1.14 :rocket:

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in v7.1.14 :rocket:

**Comment by eduludi** [comment]
IMO this should be set as a default, or at least be added to the documentation.

For those looking how to solve this, set this in your storybook configuration file:

```js
addParameters({
  jsx: {
    filterProps: val => val !== undefined,
  },
})
```

**Comment by hipstersmoothie** [comment]
I'm okay with that. Make a PR and i'll merge it!
